// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // В Prisma ORM v7 для Prisma Postgres и Accelerate достаточно одного DATABASE_URL:
    // этот же URL Prisma CLI использует для migrate/status/generate.
    url: process.env["DATABASE_URL"],
  },
});
